apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec:
  containers:
  - name: httpweb
    image: http
    ports:
    - containerPort: 8080
  - name: mynginx
    image: nginx
    ports:
    - containerPort: 8081
      
    
   
